-- NFC Business Hub — Product Core V1
-- Safe migration for the current BIGINT businesses.id schema.
-- NOTE: legacy public.services is intentionally NOT migrated automatically because its schema varies between project versions.

alter table public.businesses
  add column if not exists site_config jsonb not null default '{}'::jsonb,
  add column if not exists plan text not null default 'basic',
  add column if not exists subscription_status text not null default 'inactive',
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text;

alter table public.businesses
  drop constraint if exists businesses_plan_check;
alter table public.businesses
  add constraint businesses_plan_check
  check (plan in ('basic','pro','multi'));

alter table public.businesses
  drop constraint if exists businesses_subscription_status_check;
alter table public.businesses
  add constraint businesses_subscription_status_check
  check (subscription_status in ('inactive','trialing','active','past_due','canceled','unpaid'));

create table if not exists public.business_services (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  price numeric(10,2),
  category text,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists business_services_business_idx on public.business_services(business_id);
create index if not exists business_services_active_idx on public.business_services(business_id,active,sort_order);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  customer_name text not null,
  phone text,
  email text,
  reservation_date date not null,
  reservation_time time,
  party_size integer not null default 1 check (party_size between 1 and 99),
  status text not null default 'pending' check (status in ('pending','confirmed','completed','canceled','no_show')),
  notes text,
  source text not null default 'public_web',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reservations_business_date_idx on public.reservations(business_id,reservation_date,reservation_time);
create index if not exists reservations_business_status_idx on public.reservations(business_id,status);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  event_type text not null,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_business_created_idx on public.analytics_events(business_id,created_at desc);
create index if not exists analytics_events_business_type_idx on public.analytics_events(business_id,event_type,created_at desc);

create table if not exists public.business_locations (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  address text,
  city text,
  postal_code text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists business_locations_business_idx on public.business_locations(business_id);

create table if not exists public.nfc_plates (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  location_id bigint references public.business_locations(id) on delete set null,
  slug text,
  uid text unique,
  label text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists nfc_plates_business_idx on public.nfc_plates(business_id);
create index if not exists nfc_plates_uid_idx on public.nfc_plates(uid);

alter table public.business_services enable row level security;
alter table public.reservations enable row level security;
alter table public.analytics_events enable row level security;
alter table public.business_locations enable row level security;
alter table public.nfc_plates enable row level security;

drop policy if exists business_services_public_read on public.business_services;
create policy business_services_public_read on public.business_services
  for select using (active = true);

drop policy if exists business_services_owner_all on public.business_services;
create policy business_services_owner_all on public.business_services
  for all using (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()))
  with check (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));

drop policy if exists reservations_public_insert on public.reservations;
create policy reservations_public_insert on public.reservations
  for insert with check (true);

drop policy if exists reservations_owner_all on public.reservations;
create policy reservations_owner_all on public.reservations
  for all using (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()))
  with check (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));

drop policy if exists analytics_public_insert on public.analytics_events;
create policy analytics_public_insert on public.analytics_events
  for insert with check (true);

drop policy if exists analytics_owner_read on public.analytics_events;
create policy analytics_owner_read on public.analytics_events
  for select using (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));

drop policy if exists locations_owner_all on public.business_locations;
create policy locations_owner_all on public.business_locations
  for all using (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()))
  with check (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));

drop policy if exists plates_owner_all on public.nfc_plates;
create policy plates_owner_all on public.nfc_plates
  for all using (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()))
  with check (exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));

create or replace function public.touch_product_core_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists business_services_touch_updated_at on public.business_services;
create trigger business_services_touch_updated_at
before update on public.business_services
for each row execute function public.touch_product_core_updated_at();

drop trigger if exists reservations_touch_updated_at on public.reservations;
create trigger reservations_touch_updated_at
before update on public.reservations
for each row execute function public.touch_product_core_updated_at();
