/* NFC Business Hub — Appearance Editor V1 */
(function(){
  const URL='https://znegwqcdaxqfzbjyzija.supabase.co';
  const KEY='sb_publishable_OxUV1v29_QwhZQyy7Skg3w_-f1gTcre';
  const PRESETS={
    minimal:{name:'Minimal',accent:'#171714',bg:'#f7f6f2',card:'#ffffff',radius:18,button:'14px',font:'Inter'},
    elegant:{name:'Elegant',accent:'#8b6b3f',bg:'#f7f3ec',card:'#fffdf8',radius:24,button:'999px',font:'Georgia'},
    modern:{name:'Modern',accent:'#2457d6',bg:'#f5f7fb',card:'#ffffff',radius:14,button:'10px',font:'Inter'},
    bold:{name:'Bold',accent:'#b34d40',bg:'#f7f2f0',card:'#ffffff',radius:28,button:'999px',font:'Inter'}
  };
  let client=null,business=null,config={};
  const getClient=()=>client||(client=window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function css(){if(document.getElementById('nfc-appearance-css'))return;const s=document.createElement('style');s.id='nfc-appearance-css';s.textContent=`
    #nfcAppearanceView{padding-bottom:30px}.nfc-ap-wrap{display:grid;grid-template-columns:360px 1fr;gap:18px}.nfc-ap-panel{background:#fff;border:1px solid #e6e3db;border-radius:22px;padding:18px}.nfc-ap-panel h4{margin:0 0 12px}.nfc-ap-label{display:block;font-size:11px;font-weight:800;color:#77746d;margin:12px 0 6px}.nfc-ap-row{display:flex;gap:8px;flex-wrap:wrap}.nfc-ap-btn{border:1px solid #e6e3db;background:#fff;border-radius:12px;padding:10px 12px;font-weight:800;cursor:pointer}.nfc-ap-btn.active{border-color:#171714;box-shadow:inset 0 0 0 1px #171714;background:#faf9f5}.nfc-ap-color{width:46px;height:38px;padding:2px;border:1px solid #ddd7ca;border-radius:10px;background:#fff}.nfc-ap-range{width:100%}.nfc-ap-save{margin-top:14px;width:100%;border:0;background:#171714;color:#fff;border-radius:14px;padding:13px;font-weight:900;cursor:pointer}.nfc-ap-preview{min-height:520px;border-radius:24px;overflow:hidden;background:#f7f6f2;border:1px solid #e6e3db;display:flex;justify-content:center;align-items:flex-start;padding:34px}.nfc-ap-phone{width:min(330px,100%);background:var(--ap-bg);border-radius:34px;padding:10px;box-shadow:0 24px 70px rgba(20,20,16,.15)}.nfc-ap-screen{overflow:hidden;border-radius:27px;background:var(--ap-bg)}.nfc-ap-cover{height:135px;background:linear-gradient(135deg,var(--ap-accent),#2b2a26);display:flex;align-items:flex-end;padding:16px;color:#fff}.nfc-ap-cover h3{margin:0;font-size:23px}.nfc-ap-card{margin:10px;padding:15px;background:var(--ap-card);border-radius:var(--ap-radius);border:1px solid rgba(0,0,0,.06)}.nfc-ap-card b{display:block;font-size:15px}.nfc-ap-card span{display:block;color:#77746d;font-size:11px;margin-top:4px}.nfc-ap-card .mock-btn{display:inline-flex;margin-top:12px;padding:10px 14px;background:var(--ap-accent);color:#fff;border-radius:var(--ap-button);font-size:11px;font-weight:900}@media(max-width:850px){.nfc-ap-wrap{grid-template-columns:1fr}.nfc-ap-preview{min-height:430px}}
  `;document.head.appendChild(s)}
  function normalize(c){return Object.assign({preset:'minimal',accent:'#171714',bg:'#f7f6f2',card:'#ffffff',radius:18,button:'14px',font:'Inter'},c||{})}
  function apply(c){config=normalize(c);const root=document.documentElement;root.style.setProperty('--nfc-public-accent',config.accent);root.style.setProperty('--nfc-public-bg',config.bg);root.style.setProperty('--nfc-public-card',config.card);root.style.setProperty('--nfc-public-radius',config.radius+'px');root.style.setProperty('--nfc-public-button',config.button);window.NFCPublicAppearance=config;const p=document.querySelector('#nfcAppearancePreview .nfc-ap-phone');if(p){p.style.setProperty('--ap-accent',config.accent);p.style.setProperty('--ap-bg',config.bg);p.style.setProperty('--ap-card',config.card);p.style.setProperty('--ap-radius',config.radius+'px');p.style.setProperty('--ap-button',config.button)}
    document.querySelectorAll('[data-ap-preset]').forEach(x=>x.classList.toggle('active',x.dataset.apPreset===config.preset));
    const color=document.getElementById('nfcApColor');if(color)color.value=config.accent;
    const range=document.getElementById('nfcApRadius');if(range)range.value=config.radius;
  }
  async function loadBusiness(){const c=getClient();if(!c)return null;const {data:{user}}=await c.auth.getUser();if(!user)return null;const r=await c.from('businesses').select('id,name,owner_id,appearance_config').eq('owner_id',user.id).maybeSingle();business=r.data||null;return business}
  async function save(){const c=getClient();if(!c||!business)return;const btn=document.getElementById('nfcApSave');btn.disabled=true;btn.textContent='Guardando…';const {error}=await c.from('businesses').update({appearance_config:config}).eq('id',business.id).eq('owner_id',business.owner_id);if(error){localStorage.setItem('nfcAppearance:'+business.owner_id,JSON.stringify(config));if(window.notify)window.notify('Guardado localmente. Ejecuta el SQL de apariencia para sincronizar en todos los dispositivos.')}else{localStorage.setItem('nfcAppearance:'+business.owner_id,JSON.stringify(config));if(window.notify)window.notify('Apariencia guardada ✓')}btn.disabled=false;btn.textContent='Guardar apariencia'}
  function view(){if(document.getElementById('nfcAppearanceView'))return;const main=document.querySelector('.dash-main');if(!main)return;const v=document.createElement('div');v.id='nfcAppearanceView';v.className='dash-view';v.innerHTML=`<div class="dash-view-head"><div><h3>Apariencia</h3><p>Personaliza cómo se verá la página pública de tu negocio.</p></div></div><div class="nfc-ap-wrap"><div class="nfc-ap-panel"><h4>Estilo</h4><span class="nfc-ap-label">Preset</span><div class="nfc-ap-row">${Object.entries(PRESETS).map(([k,p])=>`<button class="nfc-ap-btn" type="button" data-ap-preset="${k}">${p.name}</button>`).join('')}</div><span class="nfc-ap-label">Color principal</span><input id="nfcApColor" class="nfc-ap-color" type="color" value="#171714"><span class="nfc-ap-label">Redondeado</span><input id="nfcApRadius" class="nfc-ap-range" type="range" min="8" max="32" value="18"><div class="nfc-ap-row" style="justify-content:space-between;color:#77746d;font-size:11px"><span>Cuadrado</span><span>Muy redondeado</span></div><button id="nfcApSave" class="nfc-ap-save" type="button">Guardar apariencia</button></div><div class="nfc-ap-preview" id="nfcAppearancePreview"><div class="nfc-ap-phone"><div class="nfc-ap-screen"><div class="nfc-ap-cover"><h3>${esc(business?.name||'TU NEGOCIO')}</h3></div><div class="nfc-ap-card"><b>Bienvenido</b><span>Así se verá el contenido de tu página pública.</span><span class="mock-btn">Contacto</span></div><div class="nfc-ap-card"><b>Servicios</b><span>Contenido adaptado a tu negocio.</span></div></div></div></div></div>`;main.appendChild(v);v.querySelectorAll('[data-ap-preset]').forEach(b=>b.addEventListener('click',()=>apply({...PRESETS[b.dataset.apPreset],preset:b.dataset.apPreset})));v.querySelector('#nfcApColor').addEventListener('input',e=>apply({...config,accent:e.target.value}));v.querySelector('#nfcApRadius').addEventListener('input',e=>apply({...config,radius:Number(e.target.value)}));v.querySelector('#nfcApSave').addEventListener('click',save);apply(config)}
  function addEntry(){const side=document.querySelector('.sidebar');if(!side||side.querySelector('[data-nfc-appearance]'))return;const item=document.createElement('div');item.className='side-item';item.dataset.nfcAppearance='1';item.textContent='🎨 Apariencia';side.appendChild(item);item.addEventListener('click',async()=>{const all=document.querySelectorAll('.dash-view[data-dash-view],.dash-view');all.forEach(x=>x.classList.remove('active'));view();document.getElementById('nfcAppearanceView')?.classList.add('active');document.querySelectorAll('.side-item').forEach(x=>x.classList.remove('active'));item.classList.add('active')})}
  async function init(){css();let tries=0;const t=setInterval(async()=>{tries++;if(!document.querySelector('.dash-main')){if(tries>40)clearInterval(t);return}const b=business||await loadBusiness();if(b){const local=localStorage.getItem('nfcAppearance:'+b.owner_id);let c=b.appearance_config;try{if(!c&&local)c=JSON.parse(local)}catch{};config=normalize(c);addEntry();clearInterval(t)}else if(tries>40)clearInterval(t)},500)}
  window.NFCAppearanceEditor={init,apply,show:view};init();
})();
