/* NFC Business Hub — Landing Design 5: Boutique Hospitality */
(function(){
  if(location.pathname.startsWith('/b/')) return;
  if(window.__nfcLandingDesign5)return; window.__nfcLandingDesign5=true;
  const r=document.documentElement;
  const css=`
:root{--d5-forest:#123d35;--d5-forest2:#0c2b26;--d5-cream:#f3efe5;--d5-stone:#d8d0c2;--d5-blue:#bfd0d1;--d5-ink:#1c2724;--d5-white:#fbfaf6;--d5-accent:#d6a875;--d5-ease:cubic-bezier(.22,.8,.2,1)}
body.d5{background:var(--d5-cream)!important;color:var(--d5-ink)!important;font-family:inherit}
body.d5 .nav{background:rgba(243,239,229,.84)!important;border:0!important;box-shadow:0 1px 0 rgba(18,61,53,.12);backdrop-filter:blur(22px)}
.d5-wrap{overflow:hidden}.d5-hero{position:relative;min-height:calc(100svh - 72px);background:var(--d5-forest);color:#f8f4eb;display:grid;align-items:end}.d5-hero:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 78% 28%,rgba(191,208,209,.16),transparent 28%),linear-gradient(115deg,transparent 46%,rgba(214,168,117,.08) 46.1%,transparent 46.5%);pointer-events:none}.d5-hero-grid{position:relative;z-index:2;width:min(1380px,calc(100% - 44px));margin:auto;display:grid;grid-template-columns:1.08fr .92fr;gap:48px;align-items:end;padding:70px 0 44px}.d5-eyebrow{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#b9cec5;font-weight:800}.d5-title{font-size:clamp(60px,8vw,128px);line-height:.86;letter-spacing:-.075em;margin:18px 0 28px;max-width:760px}.d5-title span{display:block}.d5-title em{color:var(--d5-accent);font-style:normal}.d5-copy{font-size:clamp(16px,1.4vw,20px);line-height:1.65;color:#c9d4cf;max-width:600px}.d5-hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:30px}.d5-hero-actions .btn{border-radius:2px!important;padding:15px 20px!important;min-height:52px!important}.d5-proof{display:flex;gap:30px;margin-top:30px;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#9eb1aa}.d5-visual{position:relative;height:620px;display:flex;justify-content:center;align-items:flex-end}.d5-orb{position:absolute;width:430px;height:430px;border-radius:50%;background:radial-gradient(circle,rgba(191,208,209,.28),rgba(191,208,209,.08) 42%,transparent 70%);top:80px;filter:blur(2px)}.d5-frame{position:relative;width:360px;height:600px;background:#101917;border:8px solid #0b100f;border-radius:36px 36px 30px 30px;box-shadow:0 36px 100px rgba(0,0,0,.38);transform:rotate(4deg);transition:transform .8s var(--d5-ease)}.d5-visual:hover .d5-frame{transform:rotate(0) translateY(-10px)}.d5-screen{position:absolute;inset:8px;border-radius:28px;overflow:hidden;background:#f6f2e8}.d5-screen:before{content:'';position:absolute;top:9px;left:50%;transform:translateX(-50%);width:94px;height:25px;border-radius:99px;background:#07100e;z-index:5}.d5-heroimg{height:260px;background:linear-gradient(145deg,#345c52,#86a5a2 65%,#cdbba1);display:flex;align-items:flex-end;padding:22px;color:#fff;position:relative}.d5-heroimg:after{content:'TU NEGOCIO';font-size:10px;letter-spacing:.18em;position:absolute;bottom:18px;left:20px;opacity:.85}.d5-screen-body{padding:14px}.d5-mini-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.d5-mini-actions div,.d5-mini-row{border:1px solid #ddd4c5;background:#fffdf8}.d5-mini-actions div{border-radius:12px;padding:9px 3px;text-align:center;font-size:13px}.d5-mini-actions span{display:block;font-size:7px;font-weight:800;margin-top:3px}.d5-mini-row{border-radius:13px;padding:12px;margin-top:7px;display:flex;justify-content:space-between;font-size:8px}.d5-mini-row b{font-size:9px}
.d5-ribbon{background:var(--d5-blue);color:var(--d5-forest);display:flex;justify-content:center;gap:40px;padding:15px 20px;border-top:1px solid rgba(18,61,53,.12);border-bottom:1px solid rgba(18,61,53,.12);font-size:10px;letter-spacing:.15em;text-transform:uppercase;font-weight:900;overflow:hidden}.d5-ribbon span{white-space:nowrap}
.d5-section{padding:115px 0}.d5-inner{width:min(1220px,calc(100% - 44px));margin:auto}.d5-head{display:grid;grid-template-columns:.6fr 1.4fr;gap:40px;align-items:end;margin-bottom:50px}.d5-num{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#65766f;font-weight:900}.d5-head h2{font-size:clamp(45px,6vw,84px)!important;line-height:.92!important;letter-spacing:-.065em!important;margin:0!important}.d5-head p{font-size:16px;line-height:1.75;color:#6f756f;max-width:560px;margin:0}
.d5-story{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.d5-card{min-height:420px;border-radius:24px;position:relative;overflow:hidden}.d5-card.main{background:var(--d5-forest);color:#f7f3e9;padding:38px;display:flex;flex-direction:column;justify-content:flex-end}.d5-card.main:before{content:'';position:absolute;inset:0;background:linear-gradient(160deg,transparent 30%,rgba(191,208,209,.18)),radial-gradient(circle at 80% 18%,rgba(214,168,117,.22),transparent 24%)}.d5-card.main h3{position:relative;font-size:52px;letter-spacing:-.06em;line-height:.95;margin:0 0 14px}.d5-card.main p{position:relative;color:#c9d5cf;max-width:480px;line-height:1.65}.d5-card.side{background:#e6ded1;border:1px solid rgba(18,61,53,.12);padding:30px;display:grid;align-content:space-between}.d5-stat{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid rgba(18,61,53,.16);padding-bottom:16px}.d5-stat b{font-size:44px;letter-spacing:-.06em;font-weight:500}.d5-stat span{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#66736d}
.d5-demo{background:var(--d5-stone);padding-top:130px}.d5-demo-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:70px;align-items:center}.d5-demo-copy h2{font-size:clamp(46px,6vw,78px);line-height:.92;letter-spacing:-.065em;margin:0 0 20px}.d5-demo-copy p{line-height:1.7;color:#656b67;max-width:520px}.d5-step{display:grid;grid-template-columns:38px 1fr;gap:14px;margin-top:28px}.d5-step i{width:38px;height:38px;border-radius:50%;border:1px solid rgba(18,61,53,.25);display:grid;place-items:center;font-style:normal;font-size:11px;color:var(--d5-forest)}.d5-step b{display:block;margin-bottom:4px}.d5-step span{font-size:13px;color:#6f756f;line-height:1.5}.d5-phone-stage{position:relative;min-height:600px;display:flex;justify-content:center;align-items:center}.d5-phone-stage .d5-frame{transform:rotate(-5deg);width:355px}.d5-phone-stage:hover .d5-frame{transform:rotate(0) translateY(-12px)}
.d5-dashboard{background:var(--d5-forest2);color:#f5f0e6}.d5-dashboard .d5-head p{color:#adbbb5}.d5-dashboard-shell{background:#f6f1e7;border-radius:30px;padding:12px;display:grid;grid-template-columns:230px 1fr;box-shadow:0 42px 100px rgba(0,0,0,.24)}.d5-dash-side{background:#143830;border-radius:22px;padding:22px 14px}.d5-dash-side .brand{color:#f7f2e8;font-weight:900;font-size:12px;margin-bottom:28px}.d5-dash-side .item{padding:11px 12px;border-radius:12px;color:#a9bbb4;font-size:10px;margin:4px 0}.d5-dash-side .item.active{background:#28574c;color:#fff}.d5-dash-main{color:#20312b;padding:28px}.d5-dash-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.d5-dash-top h3{margin:0;font-size:26px;letter-spacing:-.04em}.d5-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.d5-kpi{background:#fffdf8;border:1px solid #ddd4c5;border-radius:18px;padding:18px}.d5-kpi small{display:block;color:#80867f;font-size:8px;text-transform:uppercase;letter-spacing:.1em}.d5-kpi b{display:block;font-size:32px;margin-top:7px;letter-spacing:-.05em;font-weight:500}.d5-chart{margin-top:12px;background:#fffdf8;border:1px solid #ddd4c5;border-radius:20px;padding:18px}.d5-bars{height:150px;display:flex;gap:8px;align-items:end}.d5-bars i{flex:1;background:linear-gradient(180deg,#8aa9a4,#345c52);border-radius:6px 6px 2px 2px;height:var(--h)}
.d5-pricing{background:#edf1ef}.d5-price-grid{display:grid;grid-template-columns:1fr 1.18fr 1fr;gap:14px;align-items:stretch}.d5-price{background:#fffdf8;border:1px solid #d4d8d2;border-radius:24px;padding:30px;min-height:400px;display:flex;flex-direction:column;transition:transform .45s var(--d5-ease),box-shadow .45s}.d5-price:hover{transform:translateY(-8px);box-shadow:0 26px 55px rgba(18,61,53,.10)}.d5-price.featured{background:var(--d5-forest);color:#f8f4e9;border-color:var(--d5-forest);transform:translateY(-14px)}.d5-price.featured:hover{transform:translateY(-20px)}.d5-price h3{font-size:11px;text-transform:uppercase;letter-spacing:.18em}.d5-price .amount{font-size:66px;letter-spacing:-.07em;line-height:.95;margin:16px 0 4px}.d5-price .sub{font-size:11px;color:#7c827d}.d5-price.featured .sub{color:#b7c7c0}.d5-price ul{list-style:none;padding:0;margin:28px 0 0;display:grid;gap:9px;font-size:12px}.d5-price .btn{margin-top:auto}.d5-price.featured .btn.primary{background:#e8e1d5!important;color:var(--d5-forest)!important;border-color:#e8e1d5!important}
.d5-final{background:var(--d5-cream);padding:120px 0 145px}.d5-final-box{background:var(--d5-forest);color:#f7f2e8;border-radius:34px;padding:70px 42px;text-align:center;position:relative;overflow:hidden}.d5-final-box:before{content:'';position:absolute;inset:-30%;background:radial-gradient(circle at 50% 50%,rgba(191,208,209,.14),transparent 43%)}.d5-final-box>*{position:relative}.d5-final-box h2{font-size:clamp(50px,7vw,96px);line-height:.9;letter-spacing:-.07em;max-width:900px;margin:12px auto 18px}.d5-final-box p{max-width:600px;margin:auto;color:#c7d2ce;line-height:1.65}.d5-final-box .actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:30px}
@media(max-width:980px){.d5-hero-grid,.d5-demo-grid,.d5-story{grid-template-columns:1fr}.d5-visual{height:520px}.d5-dashboard-shell{grid-template-columns:1fr}.d5-dash-side{display:flex;gap:5px;overflow:auto}.d5-kpis,.d5-price-grid{grid-template-columns:1fr}.d5-price.featured{transform:none}.d5-price.featured:hover{transform:translateY(-8px)}.d5-head{grid-template-columns:1fr;gap:15px}}
@media(max-width:640px){.d5-inner{width:calc(100% - 24px)}.d5-hero-grid{width:calc(100% - 24px);padding-top:48px}.d5-title{font-size:clamp(48px,15vw,76px)}.d5-visual{height:430px}.d5-frame{width:285px;height:485px;border-width:7px}.d5-screen{border-radius:23px}.d5-section{padding:82px 0}.d5-card{min-height:300px}.d5-card.main h3{font-size:40px}.d5-demo-grid{gap:35px}.d5-phone-stage{min-height:500px}.d5-dash-main{padding:18px}.d5-kpi b{font-size:27px}.d5-final{padding:70px 0 90px}.d5-final-box{padding:52px 20px}}
`;
  const s=document.createElement('style');s.id='d5-css';s.textContent=css;document.head.appendChild(s);
  const q=(x,c=document)=>c.querySelector(x);
  const sec=id=>document.getElementById(id)?.closest('section');
  function phone(){return `<div class="d5-frame"><div class="d5-screen"><div class="d5-heroimg"></div><div class="d5-screen-body"><div class="d5-mini-actions"><div>🍽️<span>MENÚ</span></div><div>💬<span>CONTACTO</span></div><div>📅<span>RESERVAR</span></div><div>📍<span>MAPA</span></div></div><div class="d5-mini-row"><span><b>Especial del día</b><br>Experiencia destacada</span><b>24,90 €</b></div><div class="d5-mini-row"><span><b>Horario</b><br>Lun — Dom</span><b>09:00</b></div></div></div></div>`}
  function build(){document.body.classList.add('d5');
    const top=sec('top'); if(top){top.className='d5-hero';top.innerHTML=`<div class="d5-hero-grid"><div><div class="d5-eyebrow">NFC BUSINESS HUB · DIGITAL SERVICE</div><h1 class="d5-title"><span>La experiencia</span><span>empieza <em>fuera</em></span><span>de tu negocio.</span></h1><p class="d5-copy">Una placa NFC elegante, una web pensada para móvil y un dashboard que convierte cada visita en una oportunidad para el negocio.</p><div class="d5-hero-actions"><button class="btn primary" onclick="openLogin()">Crear mi acceso →</button><a class="btn" href="#demo">Ver cómo funciona</a></div><div class="d5-proof"><span>Sin app</span><span>Editable</span><span>Medible</span></div></div><div class="d5-visual"><div class="d5-orb"></div>${phone()}</div></div>`}
    const ribbon=document.createElement('div');ribbon.className='d5-ribbon';ribbon.innerHTML='<span>NFC</span><span>WEB MÓVIL</span><span>DASHBOARD</span><span>ANALÍTICA</span><span>NFC</span><span>WEB MÓVIL</span>';top?.after(ribbon);
    const como=sec('como'); if(como){como.className='d5-section';como.innerHTML=`<div class="d5-inner"><div class="d5-head"><div class="d5-num">01 / Una plataforma</div><div><h2>Diseñada para desaparecer entre las cosas buenas de tu negocio.</h2><p>No necesitas enseñar una app ni explicar un sistema. El cliente acerca el móvil y la experiencia simplemente aparece.</p></div></div><div class="d5-story"><article class="d5-card main"><h3>Menos fricción.<br>Más interacción.</h3><p>Menús, servicios, reservas, promociones, contacto y ubicación en una interfaz propia. Todo se actualiza desde un único panel.</p></article><article class="d5-card side"><div class="d5-stat"><b>1 toque</b><span>Entrada</span></div><div class="d5-stat"><b>24/7</b><span>Disponible</span></div><div class="d5-stat"><b>0 apps</b><span>Instalar</span></div></article></div></div>`}
    const demo=sec('demo'); if(demo){demo.className='d5-section d5-demo';demo.innerHTML=`<div class="d5-inner d5-demo-grid"><div class="d5-demo-copy"><div class="d5-num">02 / La experiencia</div><h2>Tu cliente no necesita aprender nada.</h2><p>La página se adapta al negocio. Los botones importantes aparecen primero, el contenido respira y cada acción tiene un destino claro.</p><div class="d5-step"><i>01</i><div><b>Acerca el móvil</b><span>La placa abre la página al instante.</span></div></div><div class="d5-step"><i>02</i><div><b>Elige una acción</b><span>Menú, reserva, WhatsApp, mapa o cualquier enlace.</span></div></div><div class="d5-step"><i>03</i><div><b>El negocio mide</b><span>Las interacciones quedan disponibles en el dashboard.</span></div></div></div><div class="d5-phone-stage">${phone()}</div></div>`}
    const dash=sec('dashboard'); if(dash){dash.className='d5-section d5-dashboard';dash.innerHTML=`<div class="d5-inner"><div class="d5-head"><div class="d5-num">03 / Control</div><div><h2>El cliente ve la página. Tú ves el negocio.</h2><p>Una interfaz de gestión pensada para hacer cambios rápidos sin depender de nadie.</p></div></div><div class="d5-dashboard-shell"><aside class="d5-dash-side"><div class="brand">NFC BUSINESS HUB</div><div class="item active">Resumen</div><div class="item">Contenido</div><div class="item">Apariencia</div><div class="item">Promociones</div><div class="item">Analítica</div></aside><main class="d5-dash-main"><div class="d5-dash-top"><h3>Resumen</h3><span>Esta semana</span></div><div class="d5-kpis"><div class="d5-kpi"><small>Visitas</small><b>2.481</b></div><div class="d5-kpi"><small>Interacciones</small><b>384</b></div><div class="d5-kpi"><small>Conversión</small><b>15,4%</b></div></div><div class="d5-chart"><small style="color:#7c827d">Actividad de los últimos 7 días</small><div class="d5-bars">${[38,52,44,68,57,88,76].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div></div></main></div></div>`}
    const plans=sec('planes'); if(plans){plans.className='d5-section d5-pricing';plans.innerHTML=`<div class="d5-inner"><div class="d5-head"><div class="d5-num">04 / Planes</div><div><h2>Una herramienta que puede crecer con el negocio.</h2><p>Empieza con lo esencial y añade profundidad cuando realmente la necesites.</p></div></div><div class="d5-price-grid"><article class="d5-price"><h3>Essential</h3><div class="amount">19€</div><div class="sub">para empezar</div><ul><li>✓ Placa NFC</li><li>✓ Web móvil</li><li>✓ Contenido básico</li><li>✓ Dashboard</li></ul><button class="btn" onclick="openLogin()">Empezar</button></article><article class="d5-price featured"><h3>Pro</h3><div class="amount">39€</div><div class="sub">la opción para crecer</div><ul><li>✓ Todo Essential</li><li>✓ Apariencia avanzada</li><li>✓ Promociones</li><li>✓ Analítica ampliada</li></ul><button class="btn primary" onclick="openLogin()">Elegir Pro</button></article><article class="d5-price"><h3>Multi</h3><div class="amount">79€</div><div class="sub">varias ubicaciones</div><ul><li>✓ Varias sedes</li><li>✓ Gestión centralizada</li><li>✓ Más control</li><li>✓ Escalable</li></ul><button class="btn" onclick="openLogin()">Hablar con nosotros</button></article></div></div>`}
    const final=document.createElement('section');final.className='d5-final';final.innerHTML='<div class="d5-inner"><div class="d5-final-box"><div class="d5-eyebrow">NFC BUSINESS HUB</div><h2>Tu negocio merece una experiencia a la altura.</h2><p>Empieza con una placa. Construye una relación digital que puedas controlar.</p><div class="actions"><button class="btn primary" onclick="openLogin()">Crear acceso →</button><a class="btn" href="#demo">Ver la demo</a></div></div></div>';document.body.appendChild(final);
    const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.style.opacity=1;e.target.style.transform='translateY(0)';io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.d5-card,.d5-head,.d5-price,.d5-dashboard-shell,.d5-final-box').forEach(el=>{el.style.opacity=0;el.style.transform='translateY(28px)';el.style.transition='opacity .8s var(--d5-ease),transform .8s var(--d5-ease)';io.observe(el)});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();
