/* NFC Business Hub — Product Core V2
   Services/catalog manager. Keeps the existing visual theme and dashboard structure. */
(function(){
  'use strict';
  const URL='https://znegwqcdaxqfzbjyzija.supabase.co';
  const KEY='sb_publishable_OxUV1v29_QwhZQyy7Skg3w_-f1gTcre';
  let client=null,business=null,view=null,rows=[];
  const TYPES={restaurant:'Carta',gym:'Clases / servicios',barbershop:'Servicios',beauty:'Tratamientos',shop:'Catálogo',bazaar:'Productos',hotel:'Servicios',other:'Servicios'};
  const getClient=()=>client||(client=window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const notify=t=>window.notify?window.notify(t):console.log(t);
  function css(){if(document.getElementById('nfc-product-v2-css'))return;const s=document.createElement('style');s.id='nfc-product-v2-css';s.textContent=`
    #nfcProductCoreView .npc-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:18px}.npc-title h3{margin:0 0 4px;font-size:28px;letter-spacing:-.04em}.npc-title p{margin:0;color:#77746d}.npc-actions{display:flex;gap:8px}.npc-btn{border:1px solid #e3e0d8;background:#fff;border-radius:12px;padding:10px 13px;font-weight:800;cursor:pointer}.npc-btn.primary{background:#171714;color:#fff;border-color:#171714}.npc-list{display:grid;gap:10px}.npc-row{display:grid;grid-template-columns:1fr auto auto;gap:14px;align-items:center;padding:15px;border:1px solid #e6e3db;background:#fff;border-radius:16px}.npc-main strong{display:block;font-size:15px}.npc-main small{display:block;color:#77746d;margin-top:4px}.npc-price{font-weight:900;white-space:nowrap}.npc-state{font-size:11px;font-weight:900;padding:6px 8px;border-radius:999px;background:#edf8f2;color:#1d7b57}.npc-state.off{background:#f3f1ed;color:#77746d}.npc-empty{padding:35px;text-align:center;color:#77746d;border:1px dashed #d8d5cc;border-radius:16px;background:#faf9f5}.npc-modal-back{position:fixed;inset:0;z-index:100001;background:rgba(20,20,16,.5);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;padding:16px}.npc-modal-back.show{display:flex}.npc-modal{width:min(520px,100%);background:#fff;border-radius:22px;padding:22px;box-shadow:0 30px 90px rgba(0,0,0,.22)}.npc-modal h3{margin:0 0 4px;font-size:24px}.npc-form{display:grid;gap:11px;margin-top:16px}.npc-form label{font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.08em;color:#6e6b64}.npc-form input,.npc-form textarea{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid #e1ded6;border-radius:11px;background:#faf9f5;outline:none;font:inherit}.npc-form textarea{min-height:86px;resize:vertical}.npc-check{display:flex;align-items:center;gap:8px;font-size:13px!important;text-transform:none!important;letter-spacing:0!important}.npc-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}@media(max-width:620px){.npc-row{grid-template-columns:1fr auto}.npc-state{grid-column:1/-1;justify-self:start}.npc-price{grid-column:2;grid-row:1}.npc-main{grid-column:1;grid-row:1}}
  `;document.head.appendChild(s)}
  async function loadBusiness(){const c=getClient();if(!c)return null;const {data:{user}}=await c.auth.getUser();if(!user)return null;const {data}=await c.from('businesses').select('id,name,business_type,owner_id').eq('owner_id',user.id).maybeSingle();business=data||null;return business}
  function ensureSidebar(){const sidebar=document.querySelector('.sidebar');if(!sidebar||sidebar.querySelector('[data-npc-services]'))return;const item=document.createElement('div');item.className='side-item';item.dataset.npcServices='1';item.textContent='📦 Contenido';sidebar.appendChild(item);item.addEventListener('click',openView);}
  async function loadRows(){const c=getClient();if(!c||!business)return;const {data,error}=await c.from('business_services').select('id,name,description,price,category,image_url,active,sort_order').eq('business_id',business.id).order('sort_order').order('name');if(error){console.error(error);rows=[];return}rows=data||[]}
  function render(){if(!view)return;const label=TYPES[business?.business_type]||'Contenido';view.innerHTML=`<div class="npc-head"><div class="npc-title"><h3>${esc(label)}</h3><p>Gestiona lo que aparece en tu web pública.</p></div><div class="npc-actions"><button class="npc-btn" id="npcRefresh">Actualizar</button><button class="npc-btn primary" id="npcAdd">+ Añadir</button></div></div><div class="npc-list">${rows.length?rows.map(r=>`<div class="npc-row"><div class="npc-main"><strong>${esc(r.name)}</strong><small>${esc(r.description||r.category||'Sin descripción')}</small></div><div class="npc-price">${r.price!=null?Number(r.price).toFixed(2)+' €':''}</div><div class="npc-state ${r.active?'':'off'}">${r.active?'Activo':'Oculto'}</div><button class="npc-btn" data-edit="${r.id}">Editar</button></div>`).join(''):`<div class="npc-empty"><strong>Aún no tienes contenido.</strong><br>Añade tu primer elemento y aparecerá en tu web.</div>`}</div>`;
    view.querySelector('#npcAdd')?.addEventListener('click',()=>openModal());view.querySelector('#npcRefresh')?.addEventListener('click',async()=>{await loadRows();render()});view.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openModal(rows.find(r=>String(r.id)===b.dataset.edit))));
  }
  function openView(){if(!document.querySelector('.dash-main'))return;const main=document.querySelector('.dash-main');if(!view){view=document.createElement('div');view.id='nfcProductCoreView';view.className='dash-view';main.appendChild(view)}document.querySelectorAll('.dash-view').forEach(x=>x.classList.remove('active'));view.classList.add('active');document.querySelectorAll('.side-item').forEach(x=>x.classList.remove('active'));document.querySelector('[data-npc-services]')?.classList.add('active');loadRows().then(render)}
  function modal(){let m=document.getElementById('nfcProductModal');if(m)return m;m=document.createElement('div');m.id='nfcProductModal';m.className='npc-modal-back';document.body.appendChild(m);return m}
  function openModal(item=null){const m=modal();m.innerHTML=`<div class="npc-modal"><h3>${item?'Editar contenido':'Añadir contenido'}</h3><p style="margin:0;color:#77746d">${esc(TYPES[business?.business_type]||'Contenido')} de tu negocio.</p><form class="npc-form"><label>Nombre<input name="name" required value="${esc(item?.name)}"></label><label>Descripción<textarea name="description">${esc(item?.description)}</textarea></label><label>Precio<input name="price" type="number" step="0.01" min="0" value="${item?.price??''}"></label><label>Categoría<input name="category" value="${esc(item?.category)}"></label><label>Imagen (URL)<input name="image_url" value="${esc(item?.image_url)}"></label><label class="npc-check"><input name="active" type="checkbox" ${item?.active!==false?'checked':''}> Visible en la web pública</label><div class="npc-modal-actions"><button type="button" class="npc-btn" id="npcCancel">Cancelar</button><button class="npc-btn primary" type="submit">${item?'Guardar cambios':'Añadir'}</button></div></form></div>`;m.classList.add('show');m.querySelector('#npcCancel').addEventListener('click',()=>m.classList.remove('show'));m.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const c=getClient();const fd=new FormData(e.currentTarget);const payload={business_id:business.id,name:String(fd.get('name')||'').trim(),description:String(fd.get('description')||'').trim()||null,price:fd.get('price')?Number(fd.get('price')):null,category:String(fd.get('category')||'').trim()||null,image_url:String(fd.get('image_url')||'').trim()||null,active:fd.get('active')==='on'};if(!payload.name)return;let res;if(item)res=await c.from('business_services').update(payload).eq('id',item.id).eq('business_id',business.id);else res=await c.from('business_services').insert({...payload,sort_order:rows.length});if(res.error){notify('No se pudo guardar');console.error(res.error);return}m.classList.remove('show');notify(item?'Contenido actualizado ✓':'Contenido añadido ✓');await loadRows();render()})}
  async function init(){css();const b=await loadBusiness();if(!b)return;ensureSidebar();if(typeof window.__nfcProductCoreV2Bound==='undefined'){window.__nfcProductCoreV2Bound=true;setTimeout(()=>{if(document.querySelector('.dash-main')&&!document.querySelector('[data-npc-services]'))ensureSidebar()},1200)}}
  window.NFCProductCoreV2={init,openView};init();
})();
